# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gold_keyword.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGroupBox, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPushButton, QScrollArea, QSizePolicy, QStatusBar,
    QTableWidget, QTableWidgetItem, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(902, 639)
        icon = QIcon()
        icon.addFile(u"\ud669\uae08\ud0a4\uc6cc\ub4dc2.ico", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(380, 20, 501, 301))
        self.lineEdit = QLineEdit(self.groupBox)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(10, 30, 311, 31))
        self.search_button = QPushButton(self.groupBox)
        self.search_button.setObjectName(u"search_button")
        self.search_button.setGeometry(QRect(340, 30, 71, 31))
        self.tableWidget = QTableWidget(self.groupBox)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(10, 70, 481, 221))
        font = QFont()
        font.setPointSize(7)
        self.tableWidget.setFont(font)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(18)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget.verticalHeader().setMinimumSectionSize(10)
        self.tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.save_button = QPushButton(self.groupBox)
        self.save_button.setObjectName(u"save_button")
        self.save_button.setGeometry(QRect(420, 30, 71, 31))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 10, 301, 71))
        font1 = QFont()
        font1.setFamilies([u"\ub9d1\uc740 \uace0\ub515"])
        font1.setPointSize(22)
        font1.setBold(True)
        self.label.setFont(font1)
        self.label.setAlignment(Qt.AlignCenter)
        self.groupBox_13 = QGroupBox(self.centralwidget)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.groupBox_13.setGeometry(QRect(20, 90, 151, 181))
        self.collect_info_keywrod_button = QPushButton(self.groupBox_13)
        self.collect_info_keywrod_button.setObjectName(u"collect_info_keywrod_button")
        self.collect_info_keywrod_button.setGeometry(QRect(10, 140, 131, 31))
        self.lineEdit_3 = QLineEdit(self.groupBox_13)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(10, 60, 131, 31))
        self.checkBox = QCheckBox(self.groupBox_13)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(10, 100, 101, 31))
        font2 = QFont()
        font2.setPointSize(8)
        self.checkBox.setFont(font2)
        self.label_6 = QLabel(self.groupBox_13)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 10, 121, 51))
        font3 = QFont()
        font3.setFamilies([u"Alef"])
        font3.setPointSize(9)
        font3.setBold(True)
        self.label_6.setFont(font3)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_6.setOpenExternalLinks(True)
        self.groupBox_14 = QGroupBox(self.centralwidget)
        self.groupBox_14.setObjectName(u"groupBox_14")
        self.groupBox_14.setGeometry(QRect(180, 90, 181, 281))
        self.generate_image_button = QPushButton(self.groupBox_14)
        self.generate_image_button.setObjectName(u"generate_image_button")
        self.generate_image_button.setGeometry(QRect(14, 230, 151, 31))
        self.lineEdit_2 = QLineEdit(self.groupBox_14)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(10, 30, 161, 181))
        self.groupBox_15 = QGroupBox(self.centralwidget)
        self.groupBox_15.setObjectName(u"groupBox_15")
        self.groupBox_15.setGeometry(QRect(20, 280, 151, 91))
        self.collect_product_keywrod_button = QPushButton(self.groupBox_15)
        self.collect_product_keywrod_button.setObjectName(u"collect_product_keywrod_button")
        self.collect_product_keywrod_button.setGeometry(QRect(10, 50, 131, 31))
        self.checkBox_2 = QCheckBox(self.groupBox_15)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(10, 20, 101, 31))
        self.checkBox_2.setFont(font2)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(650, 570, 221, 31))
        self.label_5.setFont(font3)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_5.setOpenExternalLinks(True)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(390, 570, 221, 31))
        self.label_7.setFont(font3)
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_7.setOpenExternalLinks(True)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(20, 380, 341, 211))
        self.scrollArea_log = QScrollArea(self.groupBox_2)
        self.scrollArea_log.setObjectName(u"scrollArea_log")
        self.scrollArea_log.setGeometry(QRect(10, 20, 321, 181))
        self.scrollArea_log.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 319, 179))
        self.text_log = QLabel(self.scrollAreaWidgetContents)
        self.text_log.setObjectName(u"text_log")
        self.text_log.setGeometry(QRect(0, 10, 311, 161))
        self.scrollArea_log.setWidget(self.scrollAreaWidgetContents)
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(380, 340, 501, 231))
        self.pushButton = QPushButton(self.groupBox_3)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(410, 30, 81, 31))
        self.lineEdit_4 = QLineEdit(self.groupBox_3)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(10, 30, 381, 31))
        self.textEdit = QTextEdit(self.groupBox_3)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(10, 80, 481, 141))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 902, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\ub124\uc774\ubc84 \uad11\uace0 \uc5f0\uad00\ud0a4\uc6cc\ub4dc", None))
#if QT_CONFIG(tooltip)
        self.lineEdit.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\ud0a4\uc6cc\ub4dc \uc785\ub825\ud558\uba74 \uc5f0\uad00\ud0a4\uc6cc\ub4dc\ub97c \ud655\uc778\ud560 \uc218 \uc788\uc2b5\ub2c8\ub2e4.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.search_button.setText(QCoreApplication.translate("MainWindow", u"\uac80\uc0c9", None))
        self.save_button.setText(QCoreApplication.translate("MainWindow", u"\uc800\uc7a5\ud558\uae30", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\ud669\uae08\ud0a4\uc6cc\ub4dc \ud0d0\uc0c9\uae30", None))
        self.groupBox_13.setTitle(QCoreApplication.translate("MainWindow", u"\uc815\ubcf4\uc131\ud0a4\uc6cc\ub4dc", None))
#if QT_CONFIG(tooltip)
        self.collect_info_keywrod_button.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\ud0a4\uc6cc\ub4dc\ub3c4\uad6c\uc758 \uac80\uc0c9\uacb0\uacfc \ub300\ub7c9\uc218\uc9d1</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.collect_info_keywrod_button.setText(QCoreApplication.translate("MainWindow", u"\ud0a4\uc6cc\ub4dc \ub300\ub7c9\uc218\uc9d1", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_3.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\ub124\uc774\ubc84 \uc0ac\uc804 url \uc744 \ub123\uc5b4\uc8fc\uc138\uc694</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.lineEdit_3.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\uc5ec\uae30\uc5d0 \ub124\uc774\ubc84 \ubc31\uacfc\uc0ac\uc804 \uc8fc\uc18c\ub97c \ub123\uc5b4\uc8fc\uc138\uc694</p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"\ubb38\uc11c\uc218 \ucd94\uac00\uc5ec\ubd80", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><a href=\"https://terms.naver.com/list.naver?cid=41697&amp;categoryId=41697\"><span style=\" text-decoration: underline; color:#0000ff;\">\ub124\uc774\ubc84 \ubc31\uacfc\uc0ac\uc804</span></a></p></body></html>", None))
        self.groupBox_14.setTitle(QCoreApplication.translate("MainWindow", u"\uc378\ub124\uc77c \uc790\ub3d9\uc0dd\uc131", None))
        self.generate_image_button.setText(QCoreApplication.translate("MainWindow", u"\uc0dd\uc131\ud558\uae30", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_2.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\uc378\ub124\uc77c \uc0dd\uc131\uc740 settings.txt \uc5d0\uc11c \uc218\uc815\ud558\uc2e4 \uc218 \uc788\uc2b5\ub2c8\ub2e4.</p><p>\uc774\ubbf8\uc9c0\uc758 \uac00\ub85c \uc138\ub85c \uae38\uc774, \ubc30\uacbd\uc0c9, \uae00\uc790\uc0c9, \ubc30\uacbd\uc774\ubbf8\uc9c0(\uc120\ud0dd\uc0ac\ud56d) </p><p>\uc21c\uc11c\ub300\ub85c \uc785\ub825\ud574\uc8fc\uc2dc\uba74 \ub429\ub2c8\ub2e4.</p><p><br/></p><p><br/></p><p># \uc774\ubbf8\uc9c0 \uc124\uc815(RGB 3\uc6d0\uc0c9)</p><p>IMG_WIDTH=500</p><p>IMG_HEIGHT=500</p><p>BACKGROUND_COLOR=255,255,255</p><p>TEXT_COLOR=0,0,0</p><p>BACKGROUND_IMAGE=background_image.jpg</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.groupBox_15.setTitle(QCoreApplication.translate("MainWindow", u"\uc0c1\ud488 \ud0a4\uc6cc\ub4dc", None))
        self.collect_product_keywrod_button.setText(QCoreApplication.translate("MainWindow", u"\ud0a4\uc6cc\ub4dc \ub300\ub7c9\uc218\uc9d1", None))
        self.checkBox_2.setText(QCoreApplication.translate("MainWindow", u"\ubb38\uc11c\uc218 \ucd94\uac00\uc5ec\ubd80", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><a href=\"https://blog.naver.com/dh3508?Redirect=Log&amp;logNo=222599456225&amp;from=postView\"><span style=\" text-decoration: underline; color:#0000ff;\">\ud0d0\uc0c9\uae30 \uc0ac\uc6a9\ubc29\ubc95(\ube14\ub85c\uadf8\ub85c \uc774\ub3d9)</span></a></p></body></html>", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><a href=\"https://googlechromelabs.github.io/chrome-for-testing/\"><span style=\" text-decoration: underline; color:#0000ff;\">\ucd5c\uc2e0 \ud06c\ub86c\ub4dc\ub77c\uc774\ubc84 \ub2e4\uc6b4\ub85c\ub4dc</span></a></p></body></html>", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Log", None))
        self.text_log.setText("")
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"\ub124\uc774\ubc84\uac80\uc0c9 \uc5f0\uad00\ud0a4\uc6cc\ub4dc", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\uc870\ud68c\ud558\uae30", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_4.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>\ud0a4\uc6cc\ub4dc \uc785\ub825\ud558\uba74 \uc5f0\uad00\ud0a4\uc6cc\ub4dc\ub97c \ud655\uc778\ud560 \uc218 \uc788\uc2b5\ub2c8\ub2e4.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
    # retranslateUi

